# Site settings
title: Shadi Zabad
description: 'Graduate Student at the University of Toronto'
url: 'http://shz9.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Shadi Zabad'
  email: shadi.zabad@mail.utoronto.ca
  github_username:  shz9
  linkedin_username:  shadi-zabad-57390883

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
